services:
  web:
    image: nginx
    container_name: pokedex-nginx-app

    volumes:
      - web_data:/etc/nginx/templates
      - /data/nginx-A:/usr/share/nginx/html
    ports:
      - "8080:80"

    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

volumes:
  web_data:
